export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

export default function HomePage(){
    return(
        <h1>Welcome to the home page</h1>
    )
}